/**
 * CMakeLists.txt generation
 *
 * Generates a CMakeLists.txt file for building the reconstructed project
 */

import type { ReconstructedProject, ReconstructOptions, SourceFile } from '../types.js';
import type { ResolvedTarget } from '../targets/index.js';
import type { TargetConfig } from '../config/schema.js';

/**
 * Generate CMakeLists.txt content
 */
export function generateCMakeLists(
  project: ReconstructedProject,
  options: ReconstructOptions
): string {
  const projectName = options.projectName || project.name || 'reconstructed';

  const lines: string[] = [];

  // Header comment with binary info
  lines.push('#');
  lines.push(`# ${projectName} - Reconstructed Source Code`);
  lines.push('#');
  lines.push('# Generated by ghidra-mcp reconstruct tool');
  lines.push(`# Generated at: ${new Date().toISOString()}`);
  if (project.programInfo) {
    lines.push('#');
    lines.push('# Original Binary Information:');
    lines.push(`#   Name:         ${project.programInfo.name}`);
    lines.push(`#   Format:       ${project.programInfo.format}`);
    lines.push(`#   Architecture: ${project.programInfo.architecture}`);
    lines.push(`#   Language:     ${project.programInfo.languageId}`);
    lines.push(`#   Image Base:   ${project.programInfo.imageBase}`);
    lines.push(`#   Endianness:   ${project.programInfo.endianness}`);
    lines.push(`#   Pointer Size: ${project.programInfo.pointerSize} bytes`);
    if (project.programInfo.compiler) {
      lines.push(`#   Compiler:     ${project.programInfo.compiler}`);
    }
  }
  lines.push('#');
  lines.push('');

  // CMake version and project
  lines.push('cmake_minimum_required(VERSION 3.16)');
  lines.push(`project(${sanitizeName(projectName)})`);
  lines.push('');

  // C++ standard
  lines.push('set(CMAKE_CXX_STANDARD 17)');
  lines.push('set(CMAKE_CXX_STANDARD_REQUIRED ON)');
  lines.push('set(CMAKE_EXPORT_COMPILE_COMMANDS ON)');
  lines.push('');

  // Compiler flags for decompiled code
  lines.push('# Flags for Ghidra-decompiled code (32-bit Win32 binary)');
  lines.push('if(MSVC)');
  lines.push('    add_compile_options(/W0)');
  lines.push('else()');
  lines.push('    add_compile_options(-w -fms-extensions)');
  lines.push('endif()');
  lines.push('');

  // Collect source files.
  // Build targets the Windows binary, so exclude the Mac-only modules
  // (their functions have no win: address). Shared Win/Mac functions live in
  // the normal Windows modules and are kept.
  const MAC_ONLY_PREFIXES = ['MacSpecific/', 'StormMac/'];
  const isMacOnly = (path: string) => MAC_ONLY_PREFIXES.some((p) => path.startsWith(p));

  const sourceFiles: string[] = [];
  const headerFiles: string[] = [];

  for (const [path, file] of project.files) {
    if (isMacOnly(path)) continue;
    if (file.type === 'implementation') {
      sourceFiles.push(path);
    } else if (file.type === 'header') {
      headerFiles.push(path);
    }
  }

  // Source files
  lines.push('# Source files');
  lines.push('set(SOURCES');
  for (const source of sourceFiles.sort()) {
    lines.push(`    ${source}`);
  }
  lines.push(')');
  lines.push('');

  // Header files
  lines.push('# Header files');
  lines.push('set(HEADERS');
  for (const header of headerFiles.sort()) {
    lines.push(`    ${header}`);
  }
  lines.push(')');
  lines.push('');

  // Get unique directories for include paths
  const includeDirs = getIncludeDirectories(project);

  // Include directories
  lines.push('# Include directories');
  lines.push('set(INCLUDE_DIRS');
  lines.push('    ${CMAKE_CURRENT_SOURCE_DIR}');
  for (const dir of includeDirs) {
    lines.push(`    ${dir}`);
  }
  lines.push(')');
  lines.push('');

  // Create library or executable
  lines.push('# Create library');
  lines.push(`add_library(\${PROJECT_NAME} STATIC \${SOURCES} \${HEADERS})`);
  lines.push('target_include_directories(${PROJECT_NAME} PUBLIC ${INCLUDE_DIRS})');
  lines.push('');

  // Optional: create an executable if there's a main function
  const hasMain = hasMainFunction(project);
  if (hasMain) {
    lines.push('# Executable (if main function exists)');
    lines.push(`add_executable(\${PROJECT_NAME}_exe \${SOURCES})`);
    lines.push('target_include_directories(${PROJECT_NAME}_exe PRIVATE ${INCLUDE_DIRS})');
    lines.push('');
  }

  // Installation rules
  lines.push('# Installation');
  lines.push('install(TARGETS ${PROJECT_NAME}');
  lines.push('    LIBRARY DESTINATION lib');
  lines.push('    ARCHIVE DESTINATION lib');
  lines.push(')');
  lines.push('install(FILES ${HEADERS} DESTINATION include)');
  lines.push('');

  // Export compile commands for IDE integration
  lines.push('# Export compile commands for IDE integration');
  lines.push('set(CMAKE_EXPORT_COMPILE_COMMANDS ON)');

  return lines.join('\n');
}

/**
 * Generate a simple Makefile alternative
 */
export function generateMakefile(
  project: ReconstructedProject,
  options: ReconstructOptions
): string {
  const projectName = options.projectName || project.name || 'reconstructed';

  const lines: string[] = [];

  // Variables
  lines.push(`CXX = g++`);
  lines.push(`CXXFLAGS = -std=c++17 -Wall -Wextra -I.`);
  lines.push(`TARGET = ${sanitizeName(projectName)}`);
  lines.push('');

  // Collect source files
  const sourceFiles: string[] = [];
  for (const [path, file] of project.files) {
    if (file.type === 'implementation') {
      sourceFiles.push(path);
    }
  }

  // Object files
  lines.push('SOURCES = \\');
  for (let i = 0; i < sourceFiles.length; i++) {
    const cont = i < sourceFiles.length - 1 ? ' \\' : '';
    lines.push(`    ${sourceFiles[i]}${cont}`);
  }
  lines.push('');

  lines.push('OBJECTS = $(SOURCES:.cpp=.o)');
  lines.push('');

  // Targets
  lines.push('all: $(TARGET)');
  lines.push('');

  lines.push('$(TARGET): $(OBJECTS)');
  lines.push('\t$(CXX) $(CXXFLAGS) -o $@ $^');
  lines.push('');

  lines.push('%.o: %.cpp');
  lines.push('\t$(CXX) $(CXXFLAGS) -c -o $@ $<');
  lines.push('');

  lines.push('clean:');
  lines.push('\trm -f $(OBJECTS) $(TARGET)');
  lines.push('');

  lines.push('.PHONY: all clean');

  return lines.join('\n');
}

/**
 * Get unique include directories from project structure
 */
function getIncludeDirectories(project: ReconstructedProject): string[] {
  const dirs = new Set<string>();

  for (const [path] of project.files) {
    const dir = path.split('/').slice(0, -1).join('/');
    if (dir) {
      dirs.add('${CMAKE_CURRENT_SOURCE_DIR}/' + dir);
    }
  }

  return Array.from(dirs).sort();
}

/**
 * Check if project has a main function
 */
function hasMainFunction(project: ReconstructedProject): boolean {
  for (const [, file] of project.files) {
    if (file.functions.includes('main') || file.functions.includes('_main')) {
      return true;
    }
  }
  return false;
}

/**
 * Sanitize name for use in CMake
 */
function sanitizeName(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, '_');
}

// =============================================================================
// Target-aware CMake generation
// =============================================================================

/**
 * Generate a top-level CMakeLists.txt that includes subdirectories for each target
 */
export function generateTopLevelCMake(
  project: ReconstructedProject,
  targets: Map<string, ResolvedTarget>,
  hasUnsorted: boolean,
  options: ReconstructOptions
): string {
  const projectName = options.projectName || project.name || 'reconstructed';
  const lines: string[] = [];

  lines.push('#');
  lines.push(`# ${projectName} - Reconstructed Source Code`);
  lines.push('#');
  lines.push('# Generated by ghidra-mcp reconstruct tool');
  lines.push(`# Generated at: ${new Date().toISOString()}`);
  lines.push('#');
  lines.push('');
  lines.push('cmake_minimum_required(VERSION 3.16)');
  lines.push(`project(${sanitizeName(projectName)})`);
  lines.push('');
  lines.push('set(CMAKE_CXX_STANDARD 17)');
  lines.push('set(CMAKE_CXX_STANDARD_REQUIRED ON)');
  lines.push('set(CMAKE_EXPORT_COMPILE_COMMANDS ON)');
  lines.push('');

  lines.push('# Flags for Ghidra-decompiled code (32-bit Win32 binary)');
  lines.push('if(MSVC)');
  lines.push('    add_compile_options(/W0)');
  lines.push('else()');
  lines.push('    add_compile_options(-w -fms-extensions)');
  lines.push('endif()');
  lines.push('');

  lines.push('# Targets');
  for (const [targetName] of targets) {
    lines.push(`add_subdirectory(${targetName})`);
  }
  if (hasUnsorted) {
    lines.push('add_subdirectory(unsorted)');
  }
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate CMakeLists.txt for a single target
 */
export function generateTargetCMake(
  target: ResolvedTarget,
  targetDir: string,
  files: Map<string, SourceFile>,
  options: ReconstructOptions
): string {
  const lines: string[] = [];
  const cmakeName = target.config.cmakeName || sanitizeName(target.name);

  lines.push(`# ${target.name} target`);
  if (target.config.description) {
    lines.push(`# ${target.config.description}`);
  }
  lines.push('');

  // Collect source and header files in this target directory
  const sourceFiles: string[] = [];
  const headerFiles: string[] = [];

  for (const [filePath, file] of files) {
    if (filePath.startsWith(targetDir + '/')) {
      const relativePath = filePath.substring(targetDir.length + 1);
      if (file.type === 'implementation') {
        sourceFiles.push(relativePath);
      } else if (file.type === 'header') {
        headerFiles.push(relativePath);
      }
    }
  }

  if (target.config.type === 'interface') {
    // Header-only INTERFACE library
    lines.push(`add_library(${cmakeName} INTERFACE)`);
    lines.push(`target_include_directories(${cmakeName} INTERFACE`);
    lines.push('    ${CMAKE_CURRENT_SOURCE_DIR}');
    lines.push('    ${CMAKE_CURRENT_SOURCE_DIR}/..');
    lines.push(')');
  } else {
    // Source files
    if (sourceFiles.length > 0) {
      lines.push('set(SOURCES');
      for (const source of sourceFiles.sort()) {
        lines.push(`    ${source}`);
      }
      lines.push(')');
      lines.push('');
    }

    if (headerFiles.length > 0) {
      lines.push('set(HEADERS');
      for (const header of headerFiles.sort()) {
        lines.push(`    ${header}`);
      }
      lines.push(')');
      lines.push('');
    }

    const libType = target.config.type === 'shared_library' ? 'SHARED' : 'STATIC';
    if (target.config.type === 'executable') {
      lines.push(`add_executable(${cmakeName} \${SOURCES} \${HEADERS})`);
    } else {
      lines.push(`add_library(${cmakeName} ${libType} \${SOURCES} \${HEADERS})`);
    }

    lines.push(`target_include_directories(${cmakeName} PUBLIC`);
    lines.push('    ${CMAKE_CURRENT_SOURCE_DIR}');
    lines.push('    ${CMAKE_CURRENT_SOURCE_DIR}/..');
    lines.push(')');
    lines.push('');

    // Dependencies
    if (target.config.dependencies && target.config.dependencies.length > 0) {
      const depNames = target.config.dependencies.map(dep => {
        // Look up the cmake name from the target config
        return sanitizeName(dep);
      });
      lines.push(`target_link_libraries(${cmakeName} PUBLIC ${depNames.join(' ')})`);
    }

    // Cross-target deps (informational)
    if (target.externalDeps.size > 0) {
      lines.push('');
      lines.push('# Cross-target dependencies (resolved at link time):');
      for (const [depTarget, funcs] of target.externalDeps) {
        lines.push(`#   ${depTarget}: ${funcs.slice(0, 5).join(', ')}${funcs.length > 5 ? '...' : ''}`);
      }
    }
  }

  lines.push('');
  return lines.join('\n');
}

/**
 * Generate CMakeLists.txt for unsorted functions
 */
export function generateUnsortedCMake(
  files: Map<string, SourceFile>,
  options: ReconstructOptions
): string {
  const lines: string[] = [];
  const cmakeName = sanitizeName((options.projectName || 'reconstructed') + '_unsorted');

  lines.push('# Unsorted functions (not assigned to any target)');
  lines.push('');

  const sourceFiles: string[] = [];
  const headerFiles: string[] = [];

  for (const [filePath, file] of files) {
    if (filePath.startsWith('unsorted/')) {
      const relativePath = filePath.substring('unsorted/'.length);
      if (file.type === 'implementation') {
        sourceFiles.push(relativePath);
      } else if (file.type === 'header') {
        headerFiles.push(relativePath);
      }
    }
  }

  if (sourceFiles.length > 0) {
    lines.push('set(SOURCES');
    for (const source of sourceFiles.sort()) {
      lines.push(`    ${source}`);
    }
    lines.push(')');
    lines.push('');
  }

  if (headerFiles.length > 0) {
    lines.push('set(HEADERS');
    for (const header of headerFiles.sort()) {
      lines.push(`    ${header}`);
    }
    lines.push(')');
    lines.push('');
  }

  lines.push(`add_library(${cmakeName} STATIC \${SOURCES} \${HEADERS})`);
  lines.push(`target_include_directories(${cmakeName} PUBLIC`);
  lines.push('    ${CMAKE_CURRENT_SOURCE_DIR}');
  lines.push('    ${CMAKE_CURRENT_SOURCE_DIR}/..');
  lines.push(')');
  lines.push('');

  return lines.join('\n');
}
