/**
 * AST Transformation Pipeline
 *
 * Compose multiple transformers into reusable pipelines with
 * configuration, error handling, and execution hooks.
 */

import type { ASTNode } from '../ast/nodes.js';
import {
  type Transformer,
  type TransformOptions,
  type TransformResult,
  transformWithTracking,
  sequence,
  identity,
} from './transformer.js';

/**
 * Minimal interface for injection collectors used by the pipeline.
 * The full InjectionCollector class in plugins/injection.ts implements this.
 */
export interface InjectionCollectorInterface {
  inject(injection: {
    id: string;
    type: 'include' | 'function' | 'macro' | 'typedef' | 'preamble';
    code: string;
    isSystemInclude?: boolean;
    attributes?: string[];
    priority?: number;
    dependsOn?: string[];
  }): void;
  has(id: string): boolean;
  generatePreamble(): string;
  readonly size: number;
}

// ============================================
// PIPELINE TYPES
// ============================================

/**
 * A named transformation step with optional configuration
 */
export interface TransformStep<N extends ASTNode = ASTNode> {
  /** Unique name for this step (used in logging/debugging) */
  name: string;

  /** The transformer function */
  transform: Transformer<N>;

  /** Whether this step is enabled. Default: true */
  enabled?: boolean;

  /** Optional description of what this step does */
  description?: string;
}

/**
 * Pipeline execution result with per-step tracking
 */
export interface PipelineResult<N extends ASTNode = ASTNode> {
  /** Final transformed AST */
  ast: N;

  /** Original input AST */
  original: N;

  /** Results for each step that was executed */
  steps: StepResult<N>[];

  /** Total number of changes across all steps */
  totalChanges: number;

  /** Total execution time in milliseconds */
  executionTimeMs: number;

  /** Preamble code generated by injection-aware plugins */
  preamble?: string;
}

/**
 * Result from a single pipeline step
 */
export interface StepResult<N extends ASTNode = ASTNode> {
  /** Step name */
  name: string;

  /** AST after this step */
  ast: N;

  /** Number of changes made by this step */
  changesCount: number;

  /** Whether this step was skipped */
  skipped: boolean;

  /** Execution time for this step in milliseconds */
  executionTimeMs: number;
}

/**
 * Pipeline configuration options
 */
export interface PipelineExecutionOptions extends TransformOptions {
  /** Stop execution if a step makes no changes. Default: false */
  stopOnNoChange?: boolean;

  /** Enable step-by-step result tracking. Default: false */
  trackSteps?: boolean;

  /** Callback called before each step */
  onBeforeStep?: (step: TransformStep, ast: ASTNode) => void;

  /** Callback called after each step */
  onAfterStep?: (step: TransformStep, result: StepResult) => void;

  /** Callback called on error */
  onError?: (step: TransformStep, error: Error) => void;
}

// ============================================
// PIPELINE CLASS
// ============================================

/**
 * A configurable transformation pipeline that composes multiple
 * transformers with execution control and result tracking.
 */
export class TransformPipeline<N extends ASTNode = ASTNode> {
  private steps: TransformStep<N>[] = [];
  private options: PipelineExecutionOptions = {};

  /** Optional injection collector for injection-aware plugins */
  injectionCollector?: InjectionCollectorInterface;

  /**
   * Create a new pipeline with optional initial steps
   */
  constructor(steps: TransformStep<N>[] = [], options: PipelineExecutionOptions = {}) {
    this.steps = [...steps];
    this.options = { ...options };
  }

  /**
   * Add a transformation step to the pipeline
   */
  addStep(step: TransformStep<N>): this {
    this.steps.push(step);
    return this;
  }

  /**
   * Add a simple transformer as a named step
   */
  add(name: string, transform: Transformer<N>, description?: string): this {
    return this.addStep({ name, transform, description, enabled: true });
  }

  /**
   * Insert a step at a specific position
   */
  insertAt(index: number, step: TransformStep<N>): this {
    this.steps.splice(index, 0, step);
    return this;
  }

  /**
   * Insert a step before another step by name
   */
  insertBefore(stepName: string, step: TransformStep<N>): this {
    const index = this.steps.findIndex(s => s.name === stepName);
    if (index === -1) {
      throw new Error(`Step not found: ${stepName}`);
    }
    return this.insertAt(index, step);
  }

  /**
   * Insert a step after another step by name
   */
  insertAfter(stepName: string, step: TransformStep<N>): this {
    const index = this.steps.findIndex(s => s.name === stepName);
    if (index === -1) {
      throw new Error(`Step not found: ${stepName}`);
    }
    return this.insertAt(index + 1, step);
  }

  /**
   * Remove a step by name
   */
  removeStep(name: string): this {
    const index = this.steps.findIndex(s => s.name === name);
    if (index !== -1) {
      this.steps.splice(index, 1);
    }
    return this;
  }

  /**
   * Enable or disable a step by name
   */
  setEnabled(name: string, enabled: boolean): this {
    const step = this.steps.find(s => s.name === name);
    if (step) {
      step.enabled = enabled;
    }
    return this;
  }

  /**
   * Get all steps (readonly)
   */
  getSteps(): readonly TransformStep<N>[] {
    return this.steps;
  }

  /**
   * Get a step by name
   */
  getStep(name: string): TransformStep<N> | undefined {
    return this.steps.find(s => s.name === name);
  }

  /**
   * Clear all steps from the pipeline
   */
  clear(): this {
    this.steps = [];
    return this;
  }

  /**
   * Configure pipeline options
   */
  configure(options: PipelineExecutionOptions): this {
    this.options = { ...this.options, ...options };
    return this;
  }

  /**
   * Execute the pipeline on an AST node
   */
  execute(ast: N, options?: PipelineExecutionOptions): PipelineResult<N> {
    const opts = { ...this.options, ...options };
    const startTime = performance.now();
    const stepResults: StepResult<N>[] = [];

    let currentAst = ast;
    let totalChanges = 0;

    // `changesCount` costs two full AST traversals per step. Only the two
    // features that read it are worth paying for; with neither enabled,
    // `changesCount`/`totalChanges` report 0 and the ASTs are unaffected.
    const trackChanges = opts.trackSteps === true || opts.stopOnNoChange === true;

    for (const step of this.steps) {
      // Skip disabled steps
      if (step.enabled === false) {
        if (opts.trackSteps) {
          stepResults.push({
            name: step.name,
            ast: currentAst,
            changesCount: 0,
            skipped: true,
            executionTimeMs: 0,
          });
        }
        continue;
      }

      // Before step callback
      opts.onBeforeStep?.(step as unknown as TransformStep, currentAst);

      const stepStartTime = performance.now();
      let stepResult: StepResult<N>;

      try {
        const result = transformWithTracking(currentAst, step.transform, { trackChanges });

        stepResult = {
          name: step.name,
          ast: result.ast,
          changesCount: result.changesCount,
          skipped: false,
          executionTimeMs: performance.now() - stepStartTime,
        };

        currentAst = result.ast;
        totalChanges += result.changesCount;

        // Stop if no changes and configured to do so
        if (opts.stopOnNoChange && result.changesCount === 0) {
          if (opts.trackSteps) {
            stepResults.push(stepResult);
          }
          break;
        }
      } catch (error) {
        opts.onError?.(step as unknown as TransformStep, error as Error);
        throw error;
      }

      // After step callback
      opts.onAfterStep?.(step as unknown as TransformStep, stepResult as StepResult);

      if (opts.trackSteps) {
        stepResults.push(stepResult);
      }
    }

    // Generate preamble from injection collector if present
    const preamble = this.injectionCollector && this.injectionCollector.size > 0
      ? this.injectionCollector.generatePreamble()
      : undefined;

    return {
      ast: currentAst,
      original: ast,
      steps: stepResults,
      totalChanges,
      executionTimeMs: performance.now() - startTime,
      preamble,
    };
  }

  /**
   * Convert the pipeline to a single transformer function
   */
  toTransformer(): Transformer<N> {
    const enabledSteps = this.steps
      .filter(s => s.enabled !== false)
      .map(s => s.transform as unknown as Transformer);

    if (enabledSteps.length === 0) {
      return identity as unknown as Transformer<N>;
    }

    return sequence(...enabledSteps) as unknown as Transformer<N>;
  }

  /**
   * Create a copy of this pipeline
   */
  clone(): TransformPipeline<N> {
    return new TransformPipeline(
      this.steps.map(s => ({ ...s })),
      { ...this.options }
    );
  }
}

// ============================================
// PIPELINE BUILDER
// ============================================

/**
 * Fluent builder for creating transformation pipelines
 */
export function createPipeline<N extends ASTNode = ASTNode>(
  options?: PipelineExecutionOptions
): TransformPipeline<N> {
  return new TransformPipeline<N>([], options);
}

/**
 * Create a pipeline from an array of transformers
 */
export function pipelineFromTransformers<N extends ASTNode = ASTNode>(
  transformers: Array<Transformer<N> | [string, Transformer<N>]>,
  options?: PipelineExecutionOptions
): TransformPipeline<N> {
  const pipeline = new TransformPipeline<N>([], options);

  transformers.forEach((t, i) => {
    if (Array.isArray(t)) {
      pipeline.add(t[0], t[1]);
    } else {
      pipeline.add(`step-${i}`, t);
    }
  });

  return pipeline;
}

// ============================================
// PRESET PIPELINES
// ============================================

/**
 * Create a pipeline that runs transformers until no changes occur
 */
export function createFixpointPipeline<N extends ASTNode = ASTNode>(
  transformers: Transformer<N>[],
  maxIterations: number = 10
): Transformer<N> {
  const combined = sequence(...transformers);

  return (node: N) => {
    let current = node;
    for (let i = 0; i < maxIterations; i++) {
      const result = transformWithTracking(current, combined, { trackChanges: true });
      if (result.changesCount === 0) {
        break;
      }
      current = result.ast;
    }
    return current;
  };
}

/**
 * Create a pipeline that processes nodes in parallel (for independent subtrees)
 * Note: This is a conceptual parallel - actual parallelism would require worker threads
 */
export function createParallelPipeline<N extends ASTNode = ASTNode>(
  transformers: Transformer<N>[]
): Transformer<N> {
  return (node: N) => {
    // Apply all transformers and merge results
    // In practice, this applies them sequentially but allows for future optimization
    let result = node;
    for (const t of transformers) {
      const transformed = t(result);
      if (transformed !== result) {
        result = transformed;
      }
    }
    return result;
  };
}
